apiVersion: apps/v1
kind: Deployment
metadata:
  name: scores-api
  namespace: tekton-demo
  labels:
    app: scores-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scores-api
  template:
    metadata:
      labels:
        app: scores-api
    spec:
      containers:
        - name: scores-api
          image: scores-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1"
            - name: BUILD_ID
              value: "manual"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
