apiVersion: v1
kind: Service
metadata:
  name: scores-api
  namespace: tekton-demo
  labels:
    app: scores-api
spec:
  selector:
    app: scores-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
